# Generated by Django 5.1.5 on 2025-07-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='type',
            field=models.CharField(default='Rasbery pie 3', max_length=255),
        ),
    ]
