# Generated by Django 5.1.5 on 2025-07-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_appliance_channel_slavedevice_appliance_slave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controller',
            name='type',
            field=models.CharField(default='Raspberry Pi 3', max_length=255),
        ),
        migrations.AddIndex(
            model_name='applianceusagelog',
            index=models.Index(fields=['appliance', 'start_time'], name='core_applia_applian_085f51_idx'),
        ),
        migrations.AddIndex(
            model_name='applianceusagelog',
            index=models.Index(fields=['start_time', 'stop_time'], name='core_applia_start_t_01ff39_idx'),
        ),
        migrations.AddConstraint(
            model_name='appliance',
            constraint=models.UniqueConstraint(condition=models.Q(('slave__isnull', False)), fields=('slave', 'channel'), name='unique_slave_channel'),
        ),
        migrations.AddConstraint(
            model_name='appliance',
            constraint=models.UniqueConstraint(fields=('name', 'room'), name='unique_appliance_name_per_room'),
        ),
        migrations.AddConstraint(
            model_name='applianceusagelog',
            constraint=models.CheckConstraint(condition=models.Q(('stop_time__isnull', True), ('stop_time__gt', models.F('start_time')), _connector='OR'), name='valid_time_range'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('name', 'homeowner'), name='unique_room_name_per_homeowner'),
        ),
        migrations.AddConstraint(
            model_name='slavedevice',
            constraint=models.UniqueConstraint(fields=('name', 'controller'), name='unique_slave_name_per_controller'),
        ),
    ]
